# Generated by Django 4.2.5 on 2023-10-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_defaultriskanalysis_defaultriskquestion_riskquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskanalysissignature",
            name="signatory_role",
            field=models.CharField(
                choices=[
                    ("ENG", "Engenheiro de Segurança do Trabalho"),
                    ("ADM", "Administrador"),
                    ("GER", "Gerente"),
                    ("TEC", "Técnico de Segurança do Trabalho"),
                ],
                default="TEC",
                max_length=3,
                verbose_name="Cargo do Signatário",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="riskquestion",
            name="category",
            field=models.CharField(
                choices=[
                    ("ACI", "Acidente"),
                    ("BIO", "Biológico"),
                    ("FIS", "Físico"),
                    ("QUI", "Químico"),
                ],
                max_length=3,
                verbose_name="Categoria do Risco",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENG", "Engenheiro de Segurança do Trabalho"),
                    ("ADM", "Administrador"),
                    ("GER", "Gerente"),
                    ("TEC", "Técnico de Segurança do Trabalho"),
                ],
                max_length=3,
                verbose_name="Cargo",
            ),
        ),
    ]
