# Generated by Django 4.2.5 on 2023-10-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_riskanalysissignature_signatory_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preliminaryriskanalysis",
            name="company_responsible_name",
            field=models.CharField(
                blank=True,
                max_length=250,
                verbose_name="Nome do responsável da empresa no canteiro de trabalho",
            ),
        ),
        migrations.AddField(
            model_name="preliminaryriskanalysis",
            name="company_responsible_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                verbose_name="Telefone do responsável da empresa no canteiro de trabalho",
            ),
        ),
    ]
