# Generated by Django 4.2.5 on 2023-10-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_preliminaryriskanalysis_last_update_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preliminaryriskanalysis",
            name="code",
            field=models.CharField(blank=True, max_length=20, verbose_name="Código"),
        ),
        migrations.AddField(
            model_name="preliminaryriskanalysis",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Ordem"
            ),
        ),
    ]
